### ISSUE TITLE
NO EXE FILE

### ISSUE THREAD

**Issue by marine025** [craigthomas/Chip8Python#21]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by craigthomas** [comment]
@marine025 thank you for submitting an issue to the repository! You are indeed correct - there is no `exe` file contained within the repository, or within the release zipfile or tarball. Instead, to launch the emulator, you will need to run it with a Python interpreter. For Windows, you will need to find a Python interpreter installer at:

* [https://www.python.org/downloads/windows/](https://www.python.org/downloads/windows/)

Once installed, you can then open a command window in the same directory where the Chip8Python files were decompressed and type the command:

```
python yac8e.py
```

Note that you will have to install some of the pre-requisite packages first before it will run correctly. Please refer to the documentation found in the `README.md` file under the section [Windows Installation](https://github.com/craigthomas/Chip8Python#windows-installation) for more information and step-by-step instructions on how to do that.
